apiVersion: v2
name: kioskmanager
description: A Helm chart for deploying the Kioskmanager application.
type: application
version: 0.3.5 # Your chart version
appVersion: "v1.4.0" # Your application version

# Optional Dependency: Bitnami PostgreSQL chart
dependencies:
  - name: postgresql
    version: 16.7.15 # Specify a compatible version range (check Bitnami chart releases)
    repository: "https://charts.bitnami.com/bitnami" # Use OCI repository
    # condition: postgresql.enabled means this chart is only included if values.postgresql.enabled is true
    condition: postgresql.enabled