replicaCount: 1

image:
  repository: ghcr.io/mbcom/kioskmanager
  pullPolicy: IfNotPresent
  # tag: defaults to .Chart.AppVersion
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Django specific settings
secretKey: "" # Leave empty to auto-generate, or provide a specific Django SECRET_KEY

# For the admin user creation script (reads from secrets)
adminUser: "admin"
adminPassword: "" # REQUIRED: Set this via --set or secrets file

podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000 # Port the service listens on
  targetPort: 8000 # Port your Django app listens on (Gunicorn/uWSGI)

ingress:
  enabled: true
  className: "nginx" # Your ingress controller class
  annotations:
    # Generic annotations (adjust as needed)
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod # Example for cert-manager

    # Nginx specific annotations
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # Allow large file uploads (0 = unlimited)
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300" # Increase timeout for large uploads/downloads
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"

  host: "chart-example.local" # Replace with your domain
  path: "/"
  tls: 
    enabled: false # Set to true if using TLS
    secretName: "kioskmanager"
# Persistence for media files (/app/media)
persistence:
  enabled: true
  # storageClass: "-" # Use default StorageClass or specify one, e.g., "standard", "gp2"
  accessModes:
    - ReadWriteOnce # Suitable for single Django deployment managing media
  size: 10Gi # Adjust size as needed
  mountPath: /app/content

# PostgreSQL Dependency Configuration (Bitnami chart values)
# See https://github.com/bitnami/charts/tree/main/bitnami/postgresql#parameters
postgresql:
  enabled: true # Set to false to use externalDatabase settings
  # Use auth block for credentials when deploying the Bitnami chart
  auth:
    database: "dbkioskmanager"
    username: "taskkioskmanagerpostgres"
    # password: "" # REQUIRED if postgresql.enabled=true. Set via --set or secrets file
  # Example: Enable persistence for the internal PostgreSQL DB
  primary:
    persistence:
      enabled: true
      size: 2Gi
      # storageClass: "-"

# External Database Configuration (if postgresql.enabled=false)
externalDatabase:
  host: "" # e.g., "my-external-postgres.example.com" or AWS RDS endpoint
  port: 5432
  database: "dbkioskmanager"
  username: "taskkioskmanagerpostgres"
  # password: "" # REQUIRED if postgresql.enabled=false. Set via --set or secrets file

resources: 
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi

nodeSelector: {}
tolerations: []
affinity: {}