# kioskmanager/admin.py
from django.contrib import admin
from django.contrib.auth.models import Group as AuthGroup
from .models import Browser, DisplayGroup, ContentItem, PlaylistEntry, AutomationScript
from unfold.admin import ModelAdmin, TabularInline

from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.admin import GroupAdmin as BaseGroupAdmin
from django.contrib.auth.models import User as AuthUser

from unfold.forms import AdminPasswordChangeForm, UserChangeForm, UserCreationForm
from unfold.admin import ModelAdmin


admin.site.unregister(AuthUser)
admin.site.unregister(AuthGroup)


# ─── Auth ────────────────────────────────────────────────────────────────────

@admin.register(AuthUser)
class UserAdmin(BaseUserAdmin, ModelAdmin):
    form = UserChangeForm
    add_form = UserCreationForm
    change_password_form = AdminPasswordChangeForm


@admin.register(AuthGroup)
class GroupAdmin(BaseGroupAdmin, ModelAdmin):
    pass


# ─── Permission helper ───────────────────────────────────────────────────────

def _can_manage_scripts(user):
    """Return True if the user may view and edit automation scripts.

    Grants access to superusers and to any user who holds the
    ``kioskmanager.manage_automation_scripts`` permission.  Assign this
    permission via Django admin → Auth → Users → User permissions.
    """
    return user.is_superuser or user.has_perm('kioskmanager.manage_automation_scripts')


# ─── Browser ─────────────────────────────────────────────────────────────────

@admin.register(Browser)
class BrowserAdmin(ModelAdmin):
    list_display = ('identifier', 'name', 'group', 'last_seen')
    list_filter = ('group',)
    search_fields = ('identifier', 'name')
    readonly_fields = ('identifier', 'last_seen')  # identifier is generated by the frontend
    autocomplete_fields = ['group']

    # Browsers register themselves automatically; manual creation is rarely needed.
    def has_add_permission(self, request):
        return request.user.is_superuser

    def has_delete_permission(self, request, obj=None):
        return request.user.is_superuser


# ─── Inlines ─────────────────────────────────────────────────────────────────

class PlaylistEntryInline(TabularInline):
    model = PlaylistEntry
    extra = 1
    autocomplete_fields = ['content_item']
    fields = ('order', 'content_item')
    ordering = ('order',)
    fk_name = "group"


class AutomationScriptInline(TabularInline):
    """Inline that shows which scripts are linked to a ContentItem (read-only).

    Editing is done from the AutomationScript admin.
    Only visible to users with the ``manage_automation_scripts`` permission.
    """
    model = AutomationScript.content_items.through
    extra = 0
    verbose_name = "Linked Automation Script"
    verbose_name_plural = "Linked Automation Scripts"

    def has_view_permission(self, request, obj=None):
        return _can_manage_scripts(request.user)

    def has_add_permission(self, request, obj=None):
        return _can_manage_scripts(request.user)

    def has_change_permission(self, request, obj=None):
        return _can_manage_scripts(request.user)

    def has_delete_permission(self, request, obj=None):
        return _can_manage_scripts(request.user)


class BrowserInline(TabularInline):
    """Read-only list of browsers assigned to a DisplayGroup."""
    model = Browser
    extra = 0
    can_delete = False
    readonly_fields = ('identifier', 'name', 'last_seen')
    fields = ('identifier', 'name', 'last_seen')
    verbose_name = "Assigned Browser"
    verbose_name_plural = "Assigned Browsers"

    def has_add_permission(self, request, obj=None):
        return False

    def has_change_permission(self, request, obj=None):
        return False


# ─── DisplayGroup ─────────────────────────────────────────────────────────────

@admin.register(DisplayGroup)
class DisplayGroupAdmin(ModelAdmin):
    list_display = ('name',)
    search_fields = ('name',)
    inlines = [PlaylistEntryInline, BrowserInline]
    filter_horizontal = ('managers',)

    def get_queryset(self, request):
        """Limit list view to groups the user manages (superusers see all)."""
        qs = super().get_queryset(request)
        if request.user.is_superuser:
            return qs
        return qs.filter(managers=request.user)

    def has_view_or_change_permission(self, request, obj=None):
        """Grant access only to superusers or managers of the specific group."""
        if request.user.is_superuser:
            return True
        if obj is not None:
            return obj.managers.filter(pk=request.user.pk).exists()
        return self.has_module_permission(request)

    def has_delete_permission(self, request, obj=None):
        if request.user.is_superuser:
            return True
        if obj is not None:
            return obj.managers.filter(pk=request.user.pk).exists()
        return False

    def has_add_permission(self, request):
        return request.user.is_superuser

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)

    def save_formset(self, request, form, formset, change):
        """Verify the user has change permission on the parent group before saving."""
        group_instance = form.instance
        if not self.has_view_or_change_permission(request, group_instance):
            from django.core.exceptions import PermissionDenied
            raise PermissionDenied("You do not have permission to modify this group's playlist.")
        super().save_formset(request, form, formset, change)


# ─── ContentItem ─────────────────────────────────────────────────────────────

@admin.register(ContentItem)
class ContentItemAdmin(ModelAdmin):
    """Admin view for content items (videos and websites).

    The AutomationScriptInline is only shown to users with the
    ``manage_automation_scripts`` permission, so regular content managers
    cannot see or edit scripts.
    """
    inlines = [AutomationScriptInline]
    list_display = ('title', 'content_type', 'uploaded_at')
    list_filter = ('content_type',)
    search_fields = ('title', 'url')
    fieldsets = (
        (None, {
            'fields': ('title', 'content_type')
        }),
        ('Video Details (Type: Video)', {
            'classes': ('content-type-section', 'content-type-video'),
            'fields': ('video_file',),
        }),
        ('Website Details (Type: Website)', {
            'classes': ('content-type-section', 'content-type-website'),
            'fields': ('url', 'duration'),
        }),
    )

    class Media:
        css = {'all': ('admin/css/content_item_admin.css',)}
        js = ('admin/js/content_item_admin.js',)

    def get_queryset(self, request):
        return super().get_queryset(request)

    def has_change_permission(self, request, obj=None):
        return super().has_change_permission(request, obj)

    def has_delete_permission(self, request, obj=None):
        """Only superusers may delete content items directly.

        Deleting a ContentItem removes it from all playlists.  Regular
        managers should remove it from the playlist via the DisplayGroup admin.
        """
        return request.user.is_superuser

    def has_add_permission(self, request):
        return super().has_add_permission(request)


# ─── AutomationScript (standalone) ───────────────────────────────────────────

@admin.register(AutomationScript)
class AutomationScriptAdmin(ModelAdmin):
    """Standalone admin for automation scripts.

    A script can be linked to multiple content items via the
    ``content_items`` many-to-many field.  Restricted to superusers and
    users with the ``kioskmanager.manage_automation_scripts`` permission.
    """
    list_display = ('name', 'url_pattern', 'enabled', 'order')
    list_filter = ('enabled',)
    search_fields = ('name', 'url_pattern')
    filter_horizontal = ('content_items',)

    def has_module_perms(self, request):
        return _can_manage_scripts(request.user)

    def has_view_permission(self, request, obj=None):
        return _can_manage_scripts(request.user)

    def has_add_permission(self, request):
        return _can_manage_scripts(request.user)

    def has_change_permission(self, request, obj=None):
        return _can_manage_scripts(request.user)

    def has_delete_permission(self, request, obj=None):
        return _can_manage_scripts(request.user)
