apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kioskmanager.fullname" . }}
  labels:
    {{- include "kioskmanager.labels" . | nindent 4 }}
type: Opaque
data:
  # Django Secret Key: Use provided value or generate one
  DJANGO_SECRET_KEY: {{ .Values.secretKey | default (randAlphaNum 50) | b64enc | quote }}
  # Admin Password for the startup script
  ADMIN_PASSWORD: {{ required "An admin password is required (.Values.adminPassword)" .Values.adminPassword | b64enc | quote }}
  {{- if not .Values.postgresql.enabled }}
  # External DB Password only if external DB is used
  DATABASE_PASSWORD: {{ required "External DB password required if postgresql.enabled=false (.Values.externalDatabase.password)" .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  # Note: Internal PostgreSQL password comes from the Bitnami chart's secret (e.g., {{ .Release.Name }}-postgresql)
  # We will reference that directly in the deployment env vars.
  {{- if eq .Values.auth.method "oidc" }}
  OIDC_RP_CLIENT_SECRET: {{ required "OIDC Client Secret is required if auth.method is 'oidc' (.Values.oidc.rpClientSecret can be set via --set)" (toString .Values.oidc.rpClientSecret) | b64enc | quote }}
  {{- end }}