# Generated by Django 4.2.20 on 2025-04-27 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('website', 'Website')], max_length=10)),
                ('video_file', models.FileField(blank=True, help_text="Required if type is 'Video'.", null=True, upload_to='content/videos/')),
                ('url', models.URLField(blank=True, help_text="Required if type is 'Website'.", max_length=2048, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, default=30, help_text="Duration in seconds to display (for websites). Required if type is 'Website'.", null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('managers', models.ManyToManyField(blank=True, help_text='Users who can manage content items and playlist for this group.', related_name='managed_display_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional friendly name for this browser/display', max_length=100, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(blank=True, help_text='The group this browser belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='browsers', to='kioskmanager.displaygroup')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Determines playback order (lower numbers play first).')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_appearances', to='kioskmanager.contentitem')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='kioskmanager.displaygroup')),
            ],
            options={
                'ordering': ['group', 'order'],
                'unique_together': {('group', 'order')},
            },
        ),
    ]
