# Generated by Django 4.2.21 on 2025-06-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaygroup',
            name='show_status',
            field=models.BooleanField(default=True, help_text='Show status information when switching between content items.'),
        ),
    ]
